on:
  push:
    branches:
    - main
permissions:
      id-token: write
      contents: read

jobs:
  deploy-to-qa:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out the repo
      uses: actions/checkout@v3
      with:
        ref: adf_publish
        
    
# #     - name: install ADF Utilities package
# #       run: npm install
# #       working-directory: ${{github.workspace}}
      
    - name: Login via Az module
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true 

#     - name: data-factory-deploy
#       uses: Azure/data-factory-deploy-action@v1.2.0
#       with:
#         resourceGroupName: new-rg
#         dataFactoryName: ad-gh-actions-2
#         armTemplateFile: adf-gh-dev/ARMTemplateForFactory.json
#         additionalParameters: 'factoryName=adf-gh-qa'
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: adf-gh
        template: source-adf/ARMTemplateForFactory.json
        parameters: 'factoryName=destination-adf'
  


     
  

