on:
  push:
    branches:
    - main
permissions:
      id-token: write
      contents: read

jobs:
  deploy-to-qa:
    runs-on: ubuntu-latest
    env:
      INS_LS_stgithub_connectionString: aditya
    environment:
      name: production
    steps:
    - name: Checking out the repo
      uses: actions/checkout@v3
    - name: Using the environment variables in our job
      run: |
        echo "The value of the production variable is: ${{ vars.INS_LS_stgithub }}"
        echo "The value of job level env variable is : ${{ env.INS_LS_stgithub_connectionString }}"
        
      
      
      
      # with:
      #   ref: adf_publish
        
    
# #     - name: install ADF Utilities package
# #       run: npm install
# #       working-directory: ${{github.workspace}}
      
    # - name: Login via Az module
    #   uses: azure/login@v1
    #   with:
    #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
    #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #     enable-AzPSSession: true 

    # - name: data-factory-deploy
    #   uses: Azure/data-factory-deploy-action@v1.2.0
    #   with:
    #     resourceGroupName: adf-gh
    #     dataFactoryName: destination-adf
    #     armTemplateFile: source-adf/ARMTemplateForFactory.json
    #     additionalParameters: 'factoryName=destination-adf'
    # - name: Run ARM deploy
    #   uses: azure/arm-deploy@v1
    #   with:
    #     resourceGroupName: adf-gh
    #     template: source-adf/ARMTemplateForFactory.json
    #     parameters: 'factoryName=destination-adf'
    # - name: Using the environment variables in our job
    #   environment:
        
    #   run: |
    #     echo "The value of the production variable is: ${{ env.production }}"
  


     
  

